/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthUserRouteImport } from './routes/_auth/user'
import { Route as AuthTaskIndexRouteImport } from './routes/_auth/task/index'
import { Route as AuthTaskIdRouteImport } from './routes/_auth/task/$id'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthUserRoute = AuthUserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTaskIndexRoute = AuthTaskIndexRouteImport.update({
  id: '/task/',
  path: '/task/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTaskIdRoute = AuthTaskIdRouteImport.update({
  id: '/task/$id',
  path: '/task/$id',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/sign-in': typeof SignInRoute
  '/user': typeof AuthUserRoute
  '/task/$id': typeof AuthTaskIdRoute
  '/task/': typeof AuthTaskIndexRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof SignInRoute
  '/user': typeof AuthUserRoute
  '/': typeof AuthIndexRoute
  '/task/$id': typeof AuthTaskIdRoute
  '/task': typeof AuthTaskIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/_auth/user': typeof AuthUserRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/task/$id': typeof AuthTaskIdRoute
  '/_auth/task/': typeof AuthTaskIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sign-in' | '/user' | '/task/$id' | '/task/'
  fileRoutesByTo: FileRoutesByTo
  to: '/sign-in' | '/user' | '/' | '/task/$id' | '/task'
  id:
    | '__root__'
    | '/_auth'
    | '/sign-in'
    | '/_auth/user'
    | '/_auth/'
    | '/_auth/task/$id'
    | '/_auth/task/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  SignInRoute: typeof SignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/user': {
      id: '/_auth/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof AuthUserRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/task/': {
      id: '/_auth/task/'
      path: '/task'
      fullPath: '/task/'
      preLoaderRoute: typeof AuthTaskIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/task/$id': {
      id: '/_auth/task/$id'
      path: '/task/$id'
      fullPath: '/task/$id'
      preLoaderRoute: typeof AuthTaskIdRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthUserRoute: typeof AuthUserRoute
  AuthIndexRoute: typeof AuthIndexRoute
  AuthTaskIdRoute: typeof AuthTaskIdRoute
  AuthTaskIndexRoute: typeof AuthTaskIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthUserRoute: AuthUserRoute,
  AuthIndexRoute: AuthIndexRoute,
  AuthTaskIdRoute: AuthTaskIdRoute,
  AuthTaskIndexRoute: AuthTaskIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  SignInRoute: SignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
